[2024-05-03T15:41:10.435+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T10:05:36.725645+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
