[2024-05-03T17:19:36.003+0530] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T17:19:36.009+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T11:49:28.797523+00:00 [queued]>
[2024-05-03T17:19:36.011+0530] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T11:49:28.797523+00:00 [queued]>
[2024-05-03T17:19:36.011+0530] {taskinstance.py:2303} INFO - Starting attempt 1 of 0
[2024-05-03T17:19:36.018+0530] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch_data> on 2024-05-03 11:49:28.797523+00:00
[2024-05-03T17:19:36.020+0530] {standard_task_runner.py:63} INFO - Started process 17826 to run task
[2024-05-03T17:19:36.021+0530] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_api_data', 'fetch_data', 'manual__2024-05-03T11:49:28.797523+00:00', '--job-id', '1089', '--raw', '--subdir', 'DAGS_FOLDER/async_api_dag.py', '--cfg-path', '/tmp/tmpuelq_yc5']
[2024-05-03T17:19:36.022+0530] {standard_task_runner.py:91} INFO - Job 1089: Subtask fetch_data
[2024-05-03T17:19:36.036+0530] {task_command.py:426} INFO - Running <TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T11:49:28.797523+00:00 [running]> on host ninebit5lm
[2024-05-03T17:19:36.068+0530] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_api_data' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-03T11:49:28.797523+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-03T11:49:28.797523+00:00'
[2024-05-03T17:19:36.068+0530] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T17:19:36.069+0530] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T17:19:36.069+0530] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: run() missing 1 required positional argument: 'main'
[2024-05-03T17:19:36.070+0530] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=fetch_api_data, task_id=fetch_data, execution_date=20240503T114928, start_date=20240503T114936, end_date=20240503T114936
[2024-05-03T17:19:36.070+0530] {logging_mixin.py:188} INFO - fetch_data_task failed but handled
[2024-05-03T17:19:36.076+0530] {standard_task_runner.py:110} ERROR - Failed to execute job 1089 for task fetch_data (run() missing 1 required positional argument: 'main'; 17826)
[2024-05-03T17:19:36.113+0530] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-03T17:19:36.128+0530] {local_task_job_runner.py:222} INFO - ::endgroup::
