[2024-05-03T17:11:49.251+0530] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: fetch_api_data.fetch_data manual__2024-05-03T11:41:45.448063+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
